#################################
# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.

#################################

s = "abcd"
t = "abcda"

s_list = {}
t_list = {}

for i,n in enumerate(t):
    if n not in t_list:
        t_list[n] = t.count(n)

print(t_list)

for j,m in enumerate(s):
    if t_list[m] != 0:
        t_list[m] = t_list[m] - s.count(m)
    else:
        t_list.popitem(m)

print(t_list)
for i,n in enumerate(t_list):
    if t_list[n] != 0:
        print(n)

# print(s_list)
# t_list = []
# for l in t:
#     t_list.append(l)

# for i in t_list:
#     # for j in t_list:
#     if i not in s_list:
#         print(i)
#         break
             